language: generic

matrix:
  include:
    - os: linux
      services: docker
      before_install:
        - docker pull swift:4.2
      script:
        - docker run -v "$(pwd):/root/fluent-dynamodb" swift:4.2 /bin/sh -c "cd /root/fluent-dynamodb && swift build && swift test --parallel -Xswiftc -DDEBUG"
    - os: osx
      language: swift
      osx_image: xcode10.2
      script:
        - swift build
        - swift test --parallel -Xswiftc -DDEBUG
        - swift package generate-xcodeproj
        - xcodebuild -quiet -parallel-testing-enabled YES -scheme fluent-dynamodb-Package -enableCodeCoverage YES build test
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'FluentDynamoDB'

